In [1]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
from pyspark.sql.functions import col, avg, sum, monotonically_increasing_id

In [2]:
from cassandra.cluster import Cluster

cluster = Cluster(['cassandra'])  # Replace with your Cassandra host IP(s)
session = cluster.connect()

session.execute("""
    CREATE KEYSPACE IF NOT EXISTS my_keyspace
    WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1}
""")
session.shutdown()
cluster.shutdown()

In [3]:
spark = SparkSession.builder \
    .appName("datamart") \
    .config("spark.sql.catalog.casscatalog", "com.datastax.spark.connector.datasource.CassandraCatalog") \
    .config("spark.sql.catalog.casscatalog.spark.cassandra.connection.host", "cassandra") \
    .getOrCreate()

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/04/05 23:12:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [4]:
def read_db(table_name):
    return spark.read.jdbc(url="jdbc:postgresql://postgres:5432/mydatabase",
                           table=table_name,
                           properties={
                               "user": "user",
                               "password": "password",
                               "driver": "org.postgresql.Driver"
                           })


def write_clickhouse(df, table_name, order_by):
    df.write \
        .format("clickhouse") \
        .option("host", "clickhouse") \
        .option("port", "8123") \
        .option("database", "default") \
        .option("user", "user") \
        .option("password", "password") \
        .option("table", table_name) \
        .option("order_by", order_by) \
        .mode("overwrite") \
        .save()


def write_cassandra(df, table_name, partition_by, use_existing):
    if not use_existing:
        df = df.withColumn("_id", F.monotonically_increasing_id())
        partition_by = "_id"
    df.write \
        .format("org.apache.spark.sql.cassandra") \
        .option("spark.cassandra.connection.host", "cassandra") \
        .mode("append") \
        .partitionBy(partition_by) \
        .saveAsTable(f"casscatalog.my_keyspace.{table_name}")


def write_mongodb(df, table_name):
    df.write \
        .format("mongodb") \
        .option("connection.uri", "mongodb://user:password@mongodb:27017") \
        .option("database", "mydatabase") \
        .option("collection", table_name) \
        .mode("overwrite") \
        .save()


def write_to_db(df, table_name, main_col, use_existing=False):
    write_clickhouse(df, table_name, main_col)
    write_cassandra(df, table_name, main_col, use_existing)
    write_mongodb(df, table_name)

In [5]:
p = read_db("dim_products").alias("p")
c = read_db("dim_customers").alias("c")
s = read_db("dim_sellers").alias("s")
sp = read_db("dim_suppliers").alias("sp")
st = read_db("dim_stores").alias("st")
f = read_db("fact_sales").alias("f")

In [6]:
report_products = f.join(p,f.product_id == p.id) \
            .withColumn("product_name",
                        F.concat(F.col("brand"), F.lit(": "), F.col("name"))) \
            .groupBy(F.col("product_name"), p.category) \
            .agg(
                 F.sum(f.sale_quantity).alias("total_quantity_sold"),
                 F.sum(f.sale_total_price).alias("total_revenue"),
                 F.avg(p.rating).alias("average_rating"),
                 F.sum(p.reviews).alias("total_reviews"))
write_to_db(report_products, "report_products", "product_name")
report_products.toPandas()

,product_name,category,total_quantity_sold,total_revenue,average_rating,total_reviews
0,Skynoodle: Dog Food,Cage,10,682.350000000000000000,2.6000000000000000000000,1848
1,Ntag: Bird Cage,Toy,40,1731.970000000000000000,2.6833333333333333333333,3118
2,Dabshots: Bird Cage,Food,40,1014.050000000000000000,3.4000000000000000000000,2786
3,Oyoloo: Bird Cage,Toy,34,1181.060000000000000000,3.3333333333333333333333,2966
4,Edgetag: Cat Toy,Food,29,1814.870000000000000000,3.6142857142857142857143,2419
...,...,...,...,...,...,...
3228,Ozu: Bird Cage,Cage,46,1623.530000000000000000,3.6666666666666666666667,3961
3229,Wikivu: Cat Toy,Food,12,322.320000000000000000,1.7500000000000000000000,827
3230,Ooba: Cat Toy,Food,14,714.900000000000000000,3.8500000000000000000000,916
3231,Kare: Dog Food,Toy,14,681.450000000000000000,3.7500000000000000000000,1545
3232,Dabjam: Dog Food,Cage,10,22.500000000000000000,4.6000000000000000000000,151

In [7]:
report_customers = f.join(c, c.id == f.customer_id) \
            .withColumn("customer_name",
                        F.concat(F.col("c.first_name"),
                                 F.lit(" "),
                                 F.col("c.last_name"))) \
            .groupBy(F.col("c.id").alias("customer_id"),
                     F.col("customer_name"),
                     c.country) \
            .agg(
                F.sum(f.sale_total_price).alias("total_spent"),
                (F.sum(f.sale_total_price) / F.count(f.sale_id)).alias("average_order_value"))
write_to_db(report_customers, "report_customers", "customer_id", True)
report_customers.toPandas()

,customer_id,customer_name,country,total_spent,average_order_value
0,7993,Padraic Longhirst,Russia,387.910000000000000000,387.910000000000000000
1,463,Ruthann Kerfoot,United States,422.860000000000000000,422.860000000000000000
2,7253,Nollie Pimblett,Russia,202.590000000000000000,202.590000000000000000
3,7833,Hort Baton,France,243.960000000000000000,243.960000000000000000
4,6620,Gabriella Risdale,France,46.810000000000000000,46.810000000000000000
...,...,...,...,...,...
9995,9067,Carolann Crispe,Palestinian Territory,474.010000000000000000,474.010000000000000000
9996,7466,Salvador Dummett,China,293.190000000000000000,293.190000000000000000
9997,6634,Kippy McCurry,Indonesia,479.070000000000000000,479.070000000000000000
9998,2965,Branden Bartak,China,488.820000000000000000,488.820000000000000000
9999,2555,Lynnett O'Caherny,Indonesia,482.760000000000000000,482.760000000000000000

In [8]:
report_time = f.withColumn("sale_month", F.date_trunc("month", "sale_date")) \
               .withColumn("sale_year", F.year("sale_date")) \
               .groupBy("sale_year", "sale_month") \
               .agg(
                    F.count(f.sale_id).alias("order_count"),
                    F.sum(f.sale_total_price).alias("monthly_revenue"),
                    F.avg(f.sale_total_price).alias("avg_order_size")
                )
write_to_db(report_time, "report_time", "sale_month", True)
report_time.toPandas()

,sale_year,sale_month,order_count,monthly_revenue,avg_order_size
0,2021,2021-07-01,858,220496.510000000000000000,256.9889393939393939393939
1,2021,2021-12-01,770,191368.860000000000000000,248.5309870129870129870130
2,2021,2021-10-01,892,228743.320000000000000000,256.4386995515695067264574
3,2021,2021-04-01,837,206592.820000000000000000,246.8253524492234169653524
4,2021,2021-05-01,828,211764.860000000000000000,255.7546618357487922705314
5,2021,2021-09-01,839,210623.430000000000000000,251.0410369487485101311085
6,2021,2021-06-01,822,215042.800000000000000000,261.6092457420924574209246
7,2021,2021-03-01,843,207282.200000000000000000,245.8863582443653618030842
8,2021,2021-11-01,801,200154.690000000000000000,249.8810112359550561797753
9,2021,2021-08-01,897,221275.780000000000000000,246.6842586399108138238573
10,2021,2021-02-01,739,192348.310000000000000000,260.2818809201623815967524
11,2021,2021-01-01,874,224158.540000000000000000,256.4743020594965675057208

In [9]:
report_stores = f.join(st, st.id == f.store_id) \
               .groupBy(st.name.alias("store_name"), st.city, st.country) \
               .agg(
                    F.sum(f.sale_total_price).alias("total_revenue"),
                    (F.sum(f.sale_total_price) / F.count(f.sale_id)).alias("store_average_check"))
write_to_db(report_stores, "report_stores", "store_name")
report_stores.toPandas()

,store_name,city,country,total_revenue,store_average_check
0,Wikivu,Jiangkou,China,190.630000000000000000,190.630000000000000000
1,Janyx,Milwaukee,France,169.980000000000000000,169.980000000000000000
2,Tagopia,Mikuni,South Africa,202.550000000000000000,202.550000000000000000
3,Janyx,Cap-Santé,Myanmar,288.580000000000000000,288.580000000000000000
4,LiveZ,Yanwan,China,484.490000000000000000,484.490000000000000000
...,...,...,...,...,...
9995,Youspan,Sandy Bay,China,429.710000000000000000,429.710000000000000000
9996,Zoomdog,Cangshan,Vietnam,452.300000000000000000,452.300000000000000000
9997,Lajo,Qandala,China,368.170000000000000000,368.170000000000000000
9998,Roombo,Guarenas,France,92.830000000000000000,92.830000000000000000
9999,Yakijo,São Bernardo do Campo,China,313.770000000000000000,313.770000000000000000

In [10]:
report_suppliers = f.join(sp, f.supplier_id == sp.id) \
                    .join(p, f.product_id == p.id) \
                    .groupBy(sp.name.alias("supplier_name"), sp.country) \
                    .agg(
                        sum(f.sale_total_price).alias("total_revenue_generated"),
                        avg(p.price).alias("avg_product_price"))
write_to_db(report_suppliers, "report_suppliers", "supplier_name")
report_suppliers.toPandas()

,supplier_name,country,total_revenue_generated,avg_product_price
0,Rooxo,Pakistan,37.320000000000000000,21.0900000000000000000000
1,Shuffledrive,Indonesia,1164.100000000000000000,60.2833333333333333333333
2,Demivee,Ethiopia,445.390000000000000000,12.0700000000000000000000
3,Zoonoodle,Bosnia and Herzegovina,188.440000000000000000,28.4600000000000000000000
4,Jabbersphere,Czech Republic,226.960000000000000000,16.9650000000000000000000
...,...,...,...,...
6290,Oyondu,Sweden,515.760000000000000000,66.3050000000000000000000
6291,Kwideo,Nigeria,133.630000000000000000,19.4900000000000000000000
6292,Skajo,Mongolia,431.040000000000000000,77.7900000000000000000000
6293,Oloo,Canada,142.930000000000000000,10.5700000000000000000000
6294,Topiclounge,France,97.000000000000000000,72.6400000000000000000000

In [11]:
report_quality = f.join(p, f.product_id == p.id) \
                .withColumn("product_name",
                        F.concat(F.col("brand"), F.lit(": "), F.col("name"))) \
                .groupBy("product_name", p.rating, p.reviews) \
                .agg(
                    F.sum(f.sale_quantity).alias("sales_volume"))

write_to_db(report_quality, "report_quality", "product_name")
report_quality.toPandas()

                product_name                rating  reviews  sales_volume
0             Ozu: Bird Cage  2.200000000000000000      917             5
1        Realcube: Bird Cage  1.500000000000000000      526             7
2         Skippad: Bird Cage  3.600000000000000000      594             8
3      Blognation: Bird Cage  4.100000000000000000      440             8
4          Avaveo: Bird Cage  4.600000000000000000       55             1
...                      ...                   ...      ...           ...
9993          Aimbo: Cat Toy  4.500000000000000000      786             4
9994  Jabbersphere: Dog Food  1.100000000000000000      475             5
9995         Yodo: Bird Cage  2.200000000000000000      337             4
9996        Plajo: Bird Cage  1.400000000000000000      414             9
9997         Rhyloo: Cat Toy  4.400000000000000000      224             5

[9998 rows x 4 columns]